### ISSUE TITLE
Integration of LT7911D bridge.

### ISSUE THREAD

**Issue by DhimanAirao** [SolidEva/itx-3588j-linux-kernel#1]
Hello, I am working on converting eDP data to MIPI CSI on the rk3399 processor, and I am using the LT7911D bridge. I am not able to find the driver for the same. Can you help me with it?

**Comment by SolidEva** [comment]
Sorry, I can't help. 
I'm not the maintainer of this kernel, I am merely offering a github mirror to make my work with the rk3588 chipset easier.
